// ============================================================================
// APN's hand-curated launch catalog.
// ----------------------------------------------------------------------------
// This file is the single source of truth for the static first release.
// Add only content APN has verified and has permission to feature. The site
// deliberately shows an honest empty state when a collection has no entries.
// ============================================================================

import type { AppEvent, Material, PodcastEpisode, PreachingItem } from "./types";

const publishedAt = "2026-07-17T00:00:00.000Z";
const childrensMinistriesCalendar =
  "https://upci.org/wp-content/uploads/2026/02/2026-DATES-CM.pdf";
const generalConferenceSchedule = "https://www.upcigc.net/schedule/";

// Public, source-owned UPCI images used with the relevant event cards. The
// images stay hosted by their original organization rather than being copied
// into APN's repository.
const upciEventImage = {
  worship: "https://upci.org/wp-content/uploads/2022/04/UPCI_Home_Slider8.jpg",
  singers: "https://upci.org/wp-content/uploads/2022/04/UPCI_Home_Slider4.jpg",
  baptism: "https://upci.org/wp-content/uploads/2022/04/UPCI_Home_Slider7.jpg",
  global: "https://upci.org/wp-content/uploads/2022/04/UPCI_Home_Slider6.jpg",
  community: "https://upci.org/wp-content/uploads/2022/04/UPCI_Home_Slider5.jpg",
} as const;

export const events: AppEvent[] = [
  {
    id: "north-american-jr-bible-quiz-2026",
    title: "North American Junior Bible Quiz Tournament",
    description:
      "A multi-day national tournament for junior Bible Quiz teams from across North America, listed on the UPCI Children’s Ministries 2026 calendar.",
    event_date: "2026-07-18",
    end_date: "2026-07-23",
    event_time: null,
    venue: null,
    city: "Branson",
    state: "MO",
    church_name: null,
    speaker: null,
    category: "Bible Study",
    image_url: upciEventImage.community,
    image_alt: "A UPCI community gathering.",
    highlights: [
      "Junior division teams gather for the North American tournament.",
      "Check the original Children’s Ministries calendar for host and registration updates.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "formed-2026-online",
    title: "Formed 2026",
    description:
      "A one-day online conference for teams and individuals who teach children, youth, and adults in the church. Registration includes six months of replays.",
    event_date: "2026-08-08",
    end_date: "2026-08-08",
    event_time: "9:00 AM CDT",
    venue: "Online",
    city: "Online",
    state: null,
    church_name: null,
    speaker: "LJ Harry, Jonathan Walker, Kaleb Saucer, and other UPCI teachers",
    category: "Conference",
    image_url: upciEventImage.singers,
    image_alt: "UPCI worship leaders singing together.",
    highlights: [
      "Fifteen teaching sessions plus bonus content for ministry teams.",
      "Tracks cover children, youth, and adult teaching.",
      "Registration includes replay access for six months.",
    ],
    source_url: "https://formed.upci.org/",
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "soc-global-rallies-honduras-2026",
    title: "S.O.C. Global Rallies — Honduras",
    description:
      "A scheduled S.O.C. Global Rally in Honduras, listed by UPCI Children’s Ministries as part of its 2026 global rally calendar.",
    event_date: "2026-08-10",
    end_date: "2026-08-16",
    event_time: null,
    venue: null,
    city: "Honduras",
    state: null,
    church_name: null,
    speaker: null,
    category: "Revival",
    image_url: upciEventImage.global,
    image_alt: "Children at a UPCI global ministry gathering.",
    highlights: [
      "Part of the 2026 S.O.C. Global Rallies schedule.",
      "See the official calendar for local host and participation details.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "upci-trainup-bismarck-2026",
    title: "UPCI TrainUp — Bismarck",
    description:
      "A two-day UPCI Children’s Ministries training event for local church teams, listed on the official 2026 calendar.",
    event_date: "2026-08-20",
    end_date: "2026-08-21",
    event_time: null,
    venue: null,
    city: "Bismarck",
    state: "ND",
    church_name: null,
    speaker: "Pastor Shane Paulson",
    category: "Conference",
    image_url: upciEventImage.baptism,
    image_alt: "A baptism at an Apostolic Pentecostal church.",
    highlights: [
      "Two days of Children’s Ministries training.",
      "Speaker: Pastor Shane Paulson.",
      "Follow the official calendar for registration and venue updates.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "soc-global-rallies-brazil-2026",
    title: "S.O.C. Global Rallies — Brazil",
    description:
      "A scheduled S.O.C. Global Rally in Brazil, part of the UPCI Children’s Ministries 2026 global rally calendar.",
    event_date: "2026-08-24",
    end_date: "2026-08-30",
    event_time: null,
    venue: null,
    city: "Brazil",
    state: null,
    church_name: null,
    speaker: null,
    category: "Revival",
    image_url: upciEventImage.global,
    image_alt: "Children at a UPCI global ministry gathering.",
    highlights: [
      "Part of the 2026 S.O.C. Global Rallies schedule.",
      "See the official calendar for local host and participation details.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "upci-general-conference-2026",
    title: "UPCI General Conference 2026",
    description:
      "Four days of services, seminars, ministry sessions, exhibits, and fellowship for the United Pentecostal Church International in Salt Lake City.",
    event_date: "2026-09-29",
    end_date: "2026-10-02",
    event_time: "Services begin at 6:30 PM MDT on Tuesday",
    venue: "Salt Palace Convention Center, Halls C–E",
    city: "Salt Lake City",
    state: "UT",
    church_name: null,
    speaker: "Raymond Woodward, Joel Urshan, David K. Bernard, Drew Galloway, Wayne Wyatt, and more",
    category: "Conference",
    image_url: upciEventImage.worship,
    image_alt: "A worshipper with raised hands at a UPCI gathering.",
    highlights: [
      "Global Missions service opens Tuesday evening with Raymond Woodward.",
      "Seminars, exhibits, and ministry sessions run throughout the week.",
      "General Superintendent David K. Bernard speaks Thursday evening.",
      "The schedule is tentative and all times are Mountain Daylight Time.",
    ],
    source_url: generalConferenceSchedule,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "upci-trainup-dallas-2026",
    title: "UPCI TrainUp — Dallas",
    description:
      "A two-day UPCI Children’s Ministries training event for local church teams, listed on the official 2026 calendar.",
    event_date: "2026-10-15",
    end_date: "2026-10-16",
    event_time: null,
    venue: null,
    city: "Dallas",
    state: "TX",
    church_name: null,
    speaker: "Pastor Mark Foster",
    category: "Conference",
    image_url: upciEventImage.singers,
    image_alt: "UPCI worship leaders singing together.",
    highlights: [
      "Two days of Children’s Ministries training.",
      "Speaker: Pastor Mark Foster.",
      "Follow the official calendar for registration and venue updates.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "soc-global-rallies-colombia-2026",
    title: "S.O.C. Global Rallies — Colombia",
    description:
      "A scheduled S.O.C. Global Rally in Colombia, part of the UPCI Children’s Ministries 2026 global rally calendar.",
    event_date: "2026-10-22",
    end_date: "2026-10-25",
    event_time: null,
    venue: null,
    city: "Colombia",
    state: null,
    church_name: null,
    speaker: null,
    category: "Revival",
    image_url: upciEventImage.global,
    image_alt: "Children at a UPCI global ministry gathering.",
    highlights: [
      "Part of the 2026 S.O.C. Global Rallies schedule.",
      "See the official calendar for local host and participation details.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "soc-global-rallies-bolivia-2026",
    title: "S.O.C. Global Rallies — Bolivia",
    description:
      "A scheduled S.O.C. Global Rally in Bolivia, part of the UPCI Children’s Ministries 2026 global rally calendar.",
    event_date: "2026-11-05",
    end_date: "2026-11-08",
    event_time: null,
    venue: null,
    city: "Bolivia",
    state: null,
    church_name: null,
    speaker: null,
    category: "Revival",
    image_url: upciEventImage.global,
    image_alt: "Children at a UPCI global ministry gathering.",
    highlights: [
      "Part of the 2026 S.O.C. Global Rallies schedule.",
      "See the official calendar for local host and participation details.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "soc-global-rallies-jamaica-2026",
    title: "S.O.C. Global Rallies — Jamaica",
    description:
      "A scheduled S.O.C. Global Rally in Jamaica, part of the UPCI Children’s Ministries 2026 global rally calendar.",
    event_date: "2026-11-10",
    end_date: "2026-11-15",
    event_time: null,
    venue: null,
    city: "Jamaica",
    state: null,
    church_name: null,
    speaker: null,
    category: "Revival",
    image_url: upciEventImage.global,
    image_alt: "Children at a UPCI global ministry gathering.",
    highlights: [
      "Part of the 2026 S.O.C. Global Rallies schedule.",
      "See the official calendar for local host and participation details.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "soc-global-rallies-bangladesh-2026",
    title: "S.O.C. Global Rallies — Bangladesh",
    description:
      "A scheduled S.O.C. Global Rally in Bangladesh, part of the UPCI Children’s Ministries 2026 global rally calendar.",
    event_date: "2026-12-01",
    end_date: "2026-12-07",
    event_time: null,
    venue: null,
    city: "Bangladesh",
    state: null,
    church_name: null,
    speaker: null,
    category: "Revival",
    image_url: upciEventImage.global,
    image_alt: "Children at a UPCI global ministry gathering.",
    highlights: [
      "Part of the 2026 S.O.C. Global Rallies schedule.",
      "See the official calendar for local host and participation details.",
    ],
    source_url: childrensMinistriesCalendar,
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "north-american-youth-congress-2027",
    title: "North American Youth Congress 2027",
    description:
      "The next North American Youth Congress is listed for Indianapolis in the official Kansas District UPCI event calendar.",
    event_date: "2027-07-28",
    end_date: "2027-07-30",
    event_time: null,
    venue: null,
    city: "Indianapolis",
    state: "IN",
    church_name: null,
    speaker: null,
    category: "Youth Rally",
    image_url: upciEventImage.worship,
    image_alt: "A worshipper with raised hands at a UPCI gathering.",
    highlights: [
      "A future UPCI Youth Ministries gathering for young people across North America.",
      "Dates and location are listed by the Kansas District UPCI calendar; use the original source for updates.",
    ],
    source_url: "https://www.kansasupci.org/events",
    contact_email: null,
    status: "published",
    created_at: publishedAt,
  },
];

export const preaching: PreachingItem[] = [
  {
    id: "through-new-eyes-jonathan-downs",
    title: "Through New Eyes",
    speaker: "Pastor Jonathan Downs",
    topic: null,
    scripture_reference: null,
    description: "A featured message from Calvary Chapel’s online service archive.",
    media_url: "https://www.youtube.com/watch?v=zUO2s9uim0Q",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "a-call-to-worship-kym-swile",
    title: "A Call To Worship",
    speaker: "Rev. Kym Swile",
    topic: "Worship",
    scripture_reference: null,
    description: "A featured message from Calvary Chapel’s online service archive.",
    media_url: "https://www.youtube.com/watch?v=571Dwsk1Ps8",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "faithfulness-in-a-fickle-world-john-downs",
    title: "Faithfulness in a Fickle World",
    speaker: "Bishop John Downs",
    topic: null,
    scripture_reference: null,
    description: "A featured message from Calvary Chapel’s online service archive.",
    media_url: "https://www.youtube.com/watch?v=oiH0Vm7NhvI",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "why-we-baptize-in-jesus-name",
    title: "Why We Baptize in Jesus’ Name",
    speaker: "Dr. David K. Bernard & Dr. David S. Norris",
    topic: "Baptism in Jesus' Name",
    scripture_reference: "Acts 2:38",
    description:
      "A focused Apostolic conversation on the biblical basis for baptism in the name of Jesus Christ.",
    media_url: "https://www.youtube.com/watch?v=Ji7iBbQG0Mk",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "have-you-received-the-holy-ghost",
    title: "Have You Received the Holy Ghost?",
    speaker: "Josh Herring",
    topic: "Holy Ghost",
    scripture_reference: "Acts 19:2",
    description:
      "A message centered on the promise and present work of the Holy Ghost.",
    media_url: "https://www.youtube.com/watch?v=-BltkQgj7q8",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "the-oneness-of-god-bernard-norris",
    title: "The Oneness of God",
    speaker: "Dr. David K. Bernard & Dr. David S. Norris",
    topic: "Oneness of God",
    scripture_reference: "Deuteronomy 6:4",
    description:
      "A doctrinal discussion of the biblical teaching that God is one and the identity of Jesus Christ.",
    media_url: "https://www.youtube.com/watch?v=2IoPUztXZPA",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "developing-a-praying-spirit",
    title: "Developing a Praying Spirit",
    speaker: "Josh Herring",
    topic: "Prayer",
    scripture_reference: null,
    description:
      "A practical message encouraging a deeper and more consistent life of prayer.",
    media_url: "https://www.youtube.com/watch?v=v93jFnyq70s",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "holiness-raymond-woodward",
    title: "Holiness",
    speaker: "Raymond Woodward",
    topic: "Holiness",
    scripture_reference: null,
    description:
      "A UPCI General Conference message on a consecrated life and the heart of biblical holiness.",
    media_url: "https://www.youtube.com/watch?v=la0-cCaUlCw",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "requirements-for-revival",
    title: "The Requirements for Revival",
    speaker: "Josh Herring",
    topic: "Revival",
    scripture_reference: null,
    description:
      "A call to spiritual renewal and the conditions that prepare a church for revival.",
    media_url: "https://www.youtube.com/watch?v=v18Nx2cCXac",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "apostolic-identity-josh-herring",
    title: "Apostolic Identity",
    speaker: "Josh Herring",
    topic: "Apostolic Identity",
    scripture_reference: null,
    description:
      "A message on living with a clear, biblical Apostolic identity in the present day.",
    media_url: "https://www.youtube.com/watch?v=9KU4EgzfTOA",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "evangelism-outreach-braden-andersen",
    title: "Evangelism & Outreach Presentation",
    speaker: "Dr. Braden Andersen",
    topic: "Evangelism",
    scripture_reference: null,
    description:
      "A practical UPCI district presentation focused on evangelism and reaching people with the gospel.",
    media_url: "https://www.youtube.com/watch?v=xT8u_U28DNc",
    media_type: "video",
    status: "published",
    created_at: publishedAt,
  },
];

export const podcast: PodcastEpisode[] = [
  {
    id: "cleansing-of-the-leper",
    title: "The Cleansing of the Leper",
    episode_number: null,
    guest: null,
    description: "Listen to this featured Apostolic message on Spotify.",
    duration: null,
    media_url: "https://open.spotify.com/episode/1kfHQ5k62CQgN8iUgbcbbs",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "apostolic-life-in-the-21st-century",
    title: "Apostolic Life in the 21st Century",
    episode_number: null,
    guest: "Dr. David K. Bernard",
    description:
      "Weekly teaching on Scripture, theology, Christian living, church history, and contemporary issues from an Apostolic Pentecostal perspective.",
    duration: null,
    media_url: "https://open.spotify.com/show/29oEKyZAXievg3dyzdA63s",
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "reflections-upci",
    title: "Reflections UPCI",
    episode_number: null,
    guest: "Ladies Ministries UPCI",
    description:
      "Conversations and Apostolic resources designed to encourage, equip, and empower women for life and service.",
    duration: null,
    media_url: "https://open.spotify.com/show/07xYABSct5gSONhEZ3W82a",
    status: "published",
    created_at: publishedAt,
  },
];

export const materials: Material[] = [
  {
    id: "discipleship-now",
    title: "Discipleship Now",
    category: "Discipleship & Bible Study",
    description:
      "UPCI video and small-group resources for discipleship and church growth.",
    file_type: "Link",
    file_url: "https://discipleshipnow.com/",
    is_premium: false,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "ministry-central",
    title: "Ministry Central",
    category: "Leadership & Ministry Training",
    description:
      "Training and leadership resources for ministers and local church leaders, including free Strategic Growth and SafeChurch material.",
    file_type: "Link",
    file_url: "https://ministrycentral.com/",
    is_premium: false,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "safechurch-upci",
    title: "SafeChurch UPCI",
    category: "Church Safety",
    description:
      "UPCI resources to help churches develop policies and practices that prevent abuse and create a culture of safety.",
    file_type: "Link",
    file_url: "https://upci.org/SafeChurch/",
    is_premium: false,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "upci-church-advancement",
    title: "UPCI Church Advancement",
    category: "Evangelism & Outreach",
    description:
      "Evangelism, discipleship, training, and outreach resources serving diverse communities across North America.",
    file_type: "Link",
    file_url: "https://cv.upci.org/",
    is_premium: false,
    status: "published",
    created_at: publishedAt,
  },
  {
    id: "upci-office-of-education",
    title: "UPCI Office of Education & Endorsement",
    category: "Education & Training",
    description:
      "A directory of Apostolic education, ministry training, Bible colleges, and downloadable resource information.",
    file_type: "Link",
    file_url: "https://oee.upci.org/",
    is_premium: false,
    status: "published",
    created_at: publishedAt,
  },
];
